type User @table {
  uid: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  photoUrl: String
  lastLoginAt: Timestamp
}

type DataItem @table {
  title: String!
  createdAt: Timestamp!
  description: String
  status: String
  dueDate: Date
  user: User
}